- hosts: all
  gather_facts: true
  vars:
    # ssh stuff
    ansible_become: yes
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  roles:
    - role: sem_globals
    - role: ansible-nexus-repositories
    - role: ansible-desktop-developer-software