- hosts: cc02
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:

    - name: Load requirements for git
      ansible.builtin.slurp:
        src: roles/requirements.yml
      register: requirements_content

    - name: Parse requirements.yml
      set_fact:
        git_repos: "{{ requirements_content['content'] | b64decode | from_yaml }}"

    - name: testing
      ansible.builtin.debug:
        msg: "repo: {{ src }}"
      with_items: "{{ git_repos }}"