- hosts: all
  gather_facts: true
  vars:
    ansible_become: yes
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  roles:
    - role: ansible-desktop-default-software
    - role: ansible-desktop-developer-software
    - role: ansible-antirootkits
    - role: ansible-role-clamav
    - role: ansible-hardening-addition
