- hosts: all
  gather_facts: true
  vars:
    # ssh stuff
    ansible_become: yes
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
  vars_files:
    - /var/lib/semaphore/data/sec.yml

  pre_tasks:
    - name: List current directory content
      local_action: command ls -la
      register: directory_listing

    - name: Write "hubba" to test.txt
      local_action: copy content="hubba" dest=./test.txt

  roles:
    - role: sem_globals
    - role: ansible-nexus-repositories
    - role: ansible-desktop-default-software
