- hosts: cc02
  gather_facts: true
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    gh_ssh_key: "{{ lookup('env', 'SEMAPHORE_KEY_gh_peedy2495') }}"

  tasks:

    - name: git - load playbooks
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/files/playbooks.yml"
      delegate_to: localhost
      register: playbooks_content

    - name: git - load requirements
      ansible.builtin.slurp:
        src: "{{ playbook_dir }}/roles/requirements.yml"
      delegate_to: localhost
      register: requirements_content

    - name: git - cocatentate the lists
      ansible.builtin.set_fact:
        git_repos: "{{
          playbooks_content['content'] | b64decode | from_yaml + 
          requirements_content['content'] | b64decode | from_yaml
          }}"

    - name: git - create tempdir for caching
      ansible.builtin.file:
        path: /tmp/git
        state: directory
        mode: 0777

    - debug:
        msg: "{{ gh_ssh_key }}"

    - name: git - clone repositories
      ansible.builtin.git:
        repo: "{{ item.src }}"
        version: "{{ item.version }}"
        dest: "/tmp/git/{{ item.src | regex_replace('^.*/', '') | replace('.git', '') }}"
        accept_hostkey: yes
        key_file: "{{ gh_ssh_key }}"
      with_items: "{{ git_repos }}"
      when: item.scm == 'git'