- hosts: all
  gather_facts: yes
  vars:
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
  vars_files:
    - /var/lib/semaphore/data/sec.yml

  roles:
    - role: ansible-export_airgapped
