- hosts: all
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_user: semaphore
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  pre_tasks:
    - name: reload external roles
      ansible.builtin.shell: 'export HOME=/tmp/semaphore; ansible-galaxy install -r roles/requirements.yml --force'