- hosts: all
  gather_facts: true
  vars:
    ansible_connection: local
    ansible_user: semaphore
    ansible_become: no
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"
    keyFilePath: "/home/semaphore/.ssh"

  vars_files:
    - /var/lib/semaphore/data/sec.yml

  pre_tasks:

    - name: export - git - create user ssh directory
      ansible.builtin.file:
        path: /home/semaphore/.ssh
        state: directory

    - name: export - git - deploy temporary keyfile
      ansible.builtin.copy:
        content: "{{ gh_ssh_key }}"
        dest: "{{ keyFilePath }}/id_ed25519"
        mode: 0600

    - name: export - git - create ssh config
      ansible.builtin.blockinfile:
        path: /home/semaphore/.ssh/config
        create: true
        block: |
          Host *
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
        mode: 0600

    - name: reload external roles from requirements
      ansible.builtin.shell: 'export HOME=/tmp/semaphore; ansible-galaxy install -r roles/requirements.yml --force'

    - name: reload external roles from playbooks
      ansible.builtin.shell: 'export HOME=/tmp/semaphore; ansible-galaxy install -r files/playbooks.yml --force'

    - name: export - git - remove private key
      ansible.builtin.file:
        path: "{{ keyFilePath }}"
        state: absent

    - name: Show role paths
      debug:
        msg: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"