- hosts: all
  gather_facts: true
  vars:
    # ssh stuff
    ansible_become: yes
    ansible_ssh_common_args: "-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no"

  tasks:
    
    - name: upgrade system
      block:
        - name: killing any running update process
          ansible.builtin.shell: pkill apt-get; pkill dpkg; sleep 2
        - name: upgrading
          ansible.builtin.apt:
            update_cache: yes
            upgrade: yes
          register: apt_upgrade
          retries: 5
          until: apt_upgrade is success

    - name: autoremove orphanned packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes